### PR TITLE
Re-organised docker commands to support multi-architecture

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
Hi @vfarcic 

I've split up the required docker commands into different groovy scripts for building and pushing the linux-amd64 and linux-arm images and creating and pushing the manifest list to docker hub. This way it has the same structure as before.

These files are new or modified:
- Added **dfBuildArm2.groovy** - to build and tag image for linux-arm.
- Modified **dfReleaseArm2.groovy** and moved appropriate lines to dfBuildArm2.groovy and dfManifest2.groovy - this pushes the image for linux-arm to docker hub.
- Added **dfManifest2.groovy** - to create and push manifest list for **both linux-amd64 and linux-arm**.

Please add these scripts in the correct order (**dfBuildArm2.groovy** -> **dfReleaseArm2.groovy** -> **dfManifest2.groovy**) to the Jenkins pipeline.

Personally, I think it is not needed to have all these steps separate in different groovy scripts. For maintainability reasons I would suggest to merge linux-amd64 and linux-arm as follows:

- dfBuild2.groovy = dfBuild2.groovy + dfBuildArm2.groovy
- dfRelease2.groovy = dfRelease2.groovy + dfReleaseArm2.groovy
- dfManifest2.groovy

But maybe you have a good reason to have it separate. Let me know which set-up you prefer and I'll do a PR accordingly.

### CODE REVIEW

**Comment by vfarcic** [comment]
I agree about too many steps. Let's join the files as you suggested.

I'll work on moving DFSL to the new repo during the weekend. It should be done by Sunday.

**Comment by RaymondMouthaan** [comment]
@vfarcic 

I've merged the commands into dfBuild2 and dfRelease2, also deleted not needed files.

Hope you have soon time to launch the Jenkins process to verify if the changes still works.

Also I hope you have soon some time to an issue I am facing with the use of dfp and my mqtt services. Still having issues and I don't know how to solve them.

Let me know when the movement has finished, also for dfsl, since a like to apply arm for that too. Btw if I can help, just let me know.

Greetz,
Ray

**Comment by RaymondMouthaan** [comment]
@vfarcic just noticed that the following step fails:

```
Step 11/17 : COPY docker-flow-proxy_linux_arm /usr/local/bin/docker-flow-proxy
COPY failed: stat /var/lib/docker/tmp/docker-builder008165039/docker-flow-proxy_linux_arm: no such file or directory
```

I've no idea why docker-flow-proxy_linux_arm couldn't be found, as it was before (18.04.10-29) ... 

One major difference i see is that the arm build steps are now part of the Jenkins Build step, while previously it was part of the Jenkins Release step ... I assume that  docker-flow-proxy_linux_arm is not available yet at the Jenkins Build step ...

**Comment by vfarcic** [comment]
The command that builds the arm image was moved before the command that builds the binary. I moved the build of the binary and now it's working.

**Comment by RaymondMouthaan** [comment]
I just verified using the manifest tool and can confirm that **it is indeed working** after the merging and moving, hooray 💯 ...

How is the progress on dfsl ? 
Any chance we can have a Skype session soon? :-)

Cheers!

**Comment by vfarcic** [comment]
I just moved DFSL to github.com/docker-flow/docker-flow-swarm-listener. Can you please add a Dockerfile for ARM?

I should be available tomorrow for a Skype session.

**Comment by RaymondMouthaan** [comment]
Both dfp and dfsl are working for multi architectures linux-amd64 and linux-arm 👍🏼. 

Hope we can tackle my issue tomorrow, contact me at Skype when you are available. Thanks in advance Viktor 😇

**Pull request merged**
