### PR TITLE
fix: docker-flow/docker-flow-proxy#18

### LINKED ISSUE #18: Wrong pull when using tag 18.05.08-45-linux-arm
When using dockerflow/docker-flow-proxy:18.05.08-45-linux-arm docker pulls the wrong image from docker hub. Error shown at container level is: "no suitable node ... ", which indicates wrong architecture.

I'll investigate what's wrong here and fix it as soon as possible with a PR. Meanwhile just use latest or no tag at all to pull the right image.

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
added individual manifest lists for both linux-amd64 and linux-arm
This fixes [docker-flow/docker-flow-proxy#18](https://github.com/docker-flow/docker-flow-proxy/issues/18) "Wrong pull when using tag 18.05.08-45-linux-arm".

### CODE REVIEW

**Comment by RaymondMouthaan** [comment]
Hold on for merging - need to do some more testing!

**Comment by RaymondMouthaan** [comment]
Ready to be merged, tested successfully locally.

**Comment by vfarcic** [comment]
Works like a charm (at least on Linux).

**Comment by RaymondMouthaan** [comment]
Great, happy to hear that! .. i will test later in arm too but I am pretty sure it will work 👍 .

**Pull request merged**
