### PR TITLE
Mods to the build, tag and push commands

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
- Comments added;
- Change build command;
- Switched tag and push commands
- Modifications to the build, tag and push commands

### CODE REVIEW

**Review by vfarcic — COMMENTED** [review]
Looks good except that I'd push not only `latest` but also a specific version like it was before with `docker image push vfarcic/${project}:${currentBuild.displayName}-arm`. That way users can choose what they want to use.

**Comment by RaymondMouthaan** [comment]
This still remains by line [20](https://github.com/RaymondMouthaan/jenkins-shared-libraries/blob/7090dd6a3e0a4a94bf51d443d7d284d9e6442997/vars/dfReleaseArm.groovy#L20) this pushes the image with version for linux-arm.

```
sh "docker image push vfarcic/${project}:${currentBuild.displayName}-linux-arm"
```

**Comment by vfarcic** [comment]
Sorry... My mistake... I think I should stop working when it gets close to midnight...

I wanted to say that pushing `latest-arm` (or `linux-arm`) is missing (in case someone is not interested in a particular release).

**Comment by RaymondMouthaan** [comment]
Haha you take it easy ... 

Let me explain a little more ...

If my current changes work, then I like to do similar changes to your dfRelease.groovy, when both are done and works then users can pull there images the following way:

- docker pull vfarcic/docker-flow-proxy:latest 
  - pulls the latest version for the architecture one runs, so in case of arm the latest arm image gets pulled, in case of amd64 the latest amd64 gets pulled
- docker pull vfarcic/docker-flow-proxy:{version}-linux-arm 
  - pulls the **version** for the arm architecture
- docker pull vfarcic/docker-flow-proxy:{version}-linux-amd64 
  - pulls the **version** for the amd64 architecture

So to answer your question, the first command will exactly do what you want ... right?

The tag page of docker hub would look similar like this:

screen shot 2018-04-02 at 23 40 12

**Comment by vfarcic** [comment]
Brilliant! That's what I want :).

I should have gotten more informed about Esteve's project, instead suggesting silly things. As I said, it's too late to think straight. I'll merge it tomorrow.

**Comment by RaymondMouthaan** [comment]
Victor any progress on this? 
I have some free time to continue on this :-)

**Comment by vfarcic** [comment]
Please work on it if you have free time. I was swarmed with work and could not attend to this myself.

As a side note, I created `dfReleaseArm2.groovy`. The only difference is that it pushes now to `docker-flow` instead `vfarcic`. We're in the process of moving everything to that account.

**Comment by RaymondMouthaan** [comment]
I think my last changes should be merged , then i can validate if it works with some docker commands. 

I needs to be merged because I am not able to push to docker hub using your Jenkins build process.

If it works, then I can improve the scripts more and also apply it to docker-flow-swarm-listener and maybe to Docker-flow- monitor.

**Comment by vfarcic** [comment]
Merged. Running a build now...

**Comment by RaymondMouthaan** [comment]
Great! let me watch https://hub.docker.com/r/vfarcic/docker-flow-proxy/tags/

**Comment by vfarcic** [comment]
It's failing with `Bad substitution` error message :(

https://jenkins.dockerflow.com/blue/organizations/jenkins/docker-flow-proxy/detail/master/12/pipeline

**Comment by vfarcic** [comment]
I think I know what the problem is. Running another build...

**Comment by RaymondMouthaan** [comment]
i'll keep my fingers crossed ..

**Comment by vfarcic** [comment]
Good news: build works
Bad news: getting `no matching manifest for linux/amd64 in the manifest list entries` with the latest build. I had to remove it :(

**Comment by RaymondMouthaan** [comment]
Can you explain a little more?

The build when fine, but what exactly went wrong? .. I was expecting that dfReleaseArm.groovy creates the manifest list and pushes it to docker hub.

If I remember i did some modifications also to dfRelease.groovy to do the same for amd64.

**Comment by vfarcic** [comment]
After running the pipeline, it failed to deploy a new release to my cluster. Afterward, I executed the following from my laptop.

```
➜  ~ docker image pull dockerflow/docker-flow-proxy:18.04.09-19
18.04.09-19: Pulling from dockerflow/docker-flow-proxy
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by RaymondMouthaan** [comment]
is there a way to have a chat via WhatsApp or some other app? I think it is easier to get this to work :-)

**Comment by vfarcic** [comment]
Sure. Can you ping me on HangOuts (viktor@farcic.com) or Skype (vfarcic)?

**Comment by RaymondMouthaan** [comment]
Gimme a minute .. ill install Skype first

**Pull request merged**
