### PR TITLE
Replaced manifest-tool with docker manifest

### PR DESCRIPTION
**Pull request by RaymondMouthaan**

### CODE REVIEW

**Comment by RaymondMouthaan** [comment]
Replaced manifest tool with docker manifest.

**Comment by vfarcic** [comment]
I think it's working. Can you please double check with the latest tags of DFP (I built it a few minutes ago)?

**Comment by RaymondMouthaan** [comment]
I'll check later this evening and let you know the results 👍🏼

**Comment by RaymondMouthaan** [comment]
I've checked it and latest tag works as expected 👍 .

**Pull request merged**
